#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# created author: pyTouch
# created date: 2020-1-12
# content: 爬取链家网二手房信息
# 感谢链家网（sh.lianjia.com），数据仅用于学习参考，如有其他非法目的，与本代码无关。
# 感谢小幻（https://ip.ihuan.me/）提供优质IP代理


项目爬取了上海、深圳、南宁二手房信息，并作简单分析
